### ISSUE TITLE
[Bug]: Social links are opening on the same page.

### ISSUE THREAD

**Issue by kabir0x23** [CryptoverseWeb3/Cryptoverse#31]
### Describe the bug

- Links are opening on the same page.
- Links should be opened on the new page.

### To Reproduce

- Open the website.
- Click on the Navbar social icons.
- Social handle will be open on the same page

### Expected Behavior

- Not user friendly 

### Screenshot/ Video

<p align="center">
    Social links should be opened on the new page.
</p>

![Bug-Social-links-are-opening-in](https://user-images.githubusercontent.com/44284877/178936791-9416268b-81dc-47d5-aed2-ac568a94c7e8.gif)

**Comment by rakshitgondwal** [comment]
Hey, I'm new to open source and would love to solve this issue. Can you help me with where will I find the html code for the website?

**Comment by kabir0x23** [comment]
> Basically you need to open those links on a separate page
> 
> A simple way is to give a (target = "_blank") attribute to the anchor tags `<a class="text-white" href="https://twitter.com/CryptoverseWeb3" target="_blank">`

Hey @ABHISHEK-PANDEY2 👋,
This is an open-source peoject, if you would like to resolve this issue let me know.
must give a look at these given files for instructions:
- [CONTRIBUTING.md](https://github.com/CryptoverseWeb3/Cryptoverse/blob/main/CONTRIBUTING.md)
- [installation-steps](https://github.com/CryptoverseWeb3/Cryptoverse#%EF%B8%8F-installation-steps)

If you would like to work on this issue; Let me know, and I will assign it to you.
If you need any help, feel free to ask here.

**Comment by ABHISHEK-PANDEY2** [comment]
@kabir0x23 after running "npm run dev" the project does run on local host3000 but all o see a blank page .. I don't have any knowledge of react .. but could you guide me with the next step

**Comment by kabir0x23** [comment]
> @kabir0x23 after running "npm run dev" the project does run on local host3000 but all o see a blank page .. I don't have any knowledge of react .. but could you guide me with the next step

Try: 
`http://localhost:3000/Cryptoverse`

let me know if it works

**Comment by ABHISHEK-PANDEY2** [comment]
@kabir0x23 review my PR , the telegram link might not be working
