### ISSUE TITLE
[FEATURE] Improve background design of NEWS page

### ISSUE THREAD

**Issue by kabir0x23** [CryptoverseWeb3/Cryptoverse#46]
### Detailed description

Improve background design of NEWS page

![image](https://user-images.githubusercontent.com/44284877/195839341-a693d88e-4b4a-4f04-a25b-cc58df0c083c.png)

### Context

https://cryptoverseweb3.github.io/Cryptoverse

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SDtw20** [comment]
I would like to attempt this

**Comment by kabir0x23** [comment]
Assigned to you

**Comment by SDtw20** [comment]
@kabir0x23 I've attached the screenshot of how the background looks. Kindly review. Also to maintain consistency the background for all the pages has been kept same.
<img width="1728" alt="Screenshot 2022-10-15 at 12 38 27 PM" src="https://user-images.githubusercontent.com/115735408/195974274-f5da9abe-ae51-450e-ada3-2c964dc042c5.png">
